import Image from "next/image";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy — Hanif Studio",
  description:
    "Privacy Policy for Hanif Studio. Learn how we collect, use, and protect your personal data when you use our services.",
  robots: {
    index: true,
    follow: true,
  },
};

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen relative bg-gray-100">
      {/* Hero Background */}
      <div className="absolute top-0 w-full z-0 h-[300px] blur-3xl overflow-hidden">
        <Image
          src="https://hoirqrkdgbmvpwutwuwj.supabase.co/storage/v1/object/public/assets/assets/55089b0e-fd30-4b07-881c-69dd9c26979b_3840w.jpg"
          alt="Background"
          fill
          priority
          className="object-cover"
        />
      </div>

      <div className="relative z-10">
        <Header />
        <main className="max-w-4xl mx-auto px-5 py-16 md:py-20">
          <h1 className="text-4xl md:text-5xl font-medium mb-4 tracking-tighter">
            Privacy Policy
          </h1>
          <p className="text-black/60 font-geist mb-8">
            Effective date: January 24, 2025
          </p>

          <div className="prose prose-lg max-w-none">
            <section className="mb-8">
              <h2 className="text-2xl font-medium mb-4 tracking-tight">
                Introduction
              </h2>
              <p className="text-black/70 font-geist leading-relaxed mb-4">
                Welcome to Hanif Studio. Hanif Studio ("us", "we", or "our")
                operates https://hanif.studio (hereinafter referred to as
                "Service").
              </p>
              <p className="text-black/70 font-geist leading-relaxed mb-4">
                Our Privacy Policy governs your visit to https://hanif.studio,
                and explains how we collect, safeguard and disclose information
                that results from your use of our Service.
              </p>
              <p className="text-black/70 font-geist leading-relaxed">
                We use your data to provide and improve Service. By using
                Service, you agree to the collection and use of information in
                accordance with this policy. Unless otherwise defined in this
                Privacy Policy, the terms used in this Privacy Policy have the
                same meanings as in our Terms and Conditions.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-medium mb-4 tracking-tight">
                Definitions
              </h2>
              <div className="space-y-3">
                <p className="text-black/70 font-geist leading-relaxed">
                  <strong className="text-black">SERVICE</strong> means the
                  https://hanif.studio website operated by Hanif Studio.
                </p>
                <p className="text-black/70 font-geist leading-relaxed">
                  <strong className="text-black">PERSONAL DATA</strong> means
                  data about a living individual who can be identified from
                  those data (or from those and other information either in our
                  possession or likely to come into our possession).
                </p>
                <p className="text-black/70 font-geist leading-relaxed">
                  <strong className="text-black">USAGE DATA</strong> is data
                  collected automatically either generated by the use of Service
                  or from Service infrastructure itself (for example, the
                  duration of a page visit).
                </p>
                <p className="text-black/70 font-geist leading-relaxed">
                  <strong className="text-black">COOKIES</strong> are small
                  files stored on your device (computer or mobile device).
                </p>
                <p className="text-black/70 font-geist leading-relaxed">
                  <strong className="text-black">DATA CONTROLLER</strong> means
                  a natural or legal person who (either alone or jointly or in
                  common with other persons) determines the purposes for which
                  and the manner in which any personal data are, or are to be,
                  processed. For the purpose of this Privacy Policy, we are a
                  Data Controller of your data.
                </p>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-medium mb-4 tracking-tight">
                Information Collection and Use
              </h2>
              <p className="text-black/70 font-geist leading-relaxed mb-4">
                We collect several different types of information for various
                purposes to provide and improve our Service to you.
              </p>

              <h3 className="text-xl font-medium mb-3 tracking-tight mt-6">
                Personal Data
              </h3>
              <p className="text-black/70 font-geist leading-relaxed mb-4">
                While using our Service, we may ask you to provide us with
                certain personally identifiable information that can be used to
                contact or identify you ("Personal Data"). Personally
                identifiable information may include, but is not limited to:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-black/70 font-geist mb-4">
                <li>Email address</li>
                <li>Cookies and Usage Data</li>
              </ul>

              <h3 className="text-xl font-medium mb-3 tracking-tight mt-6">
                Usage Data
              </h3>
              <p className="text-black/70 font-geist leading-relaxed mb-4">
                We may also collect information that your browser sends whenever
                you visit our Service or when you access Service by or through a
                mobile device ("Usage Data").
              </p>
              <p className="text-black/70 font-geist leading-relaxed">
                This Usage Data may include information such as your computer's
                Internet Protocol address (e.g. IP address), browser type,
                browser version, the pages of our Service that you visit, the
                time and date of your visit, the time spent on those pages,
                unique device identifiers and other diagnostic data.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-medium mb-4 tracking-tight">
                Tracking & Cookies Data
              </h2>
              <p className="text-black/70 font-geist leading-relaxed mb-4">
                We use cookies and similar tracking technologies to track the
                activity on our Service and we hold certain information.
              </p>
              <p className="text-black/70 font-geist leading-relaxed mb-4">
                Cookies are files with a small amount of data which may include
                an anonymous unique identifier. Cookies are sent to your browser
                from a website and stored on your device.
              </p>
              <p className="text-black/70 font-geist leading-relaxed mb-4">
                Examples of Cookies we use:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-black/70 font-geist">
                <li>
                  <strong className="text-black">Session Cookies:</strong> We
                  use Session Cookies to operate our Service.
                </li>
                <li>
                  <strong className="text-black">Preference Cookies:</strong> We
                  use Preference Cookies to remember your preferences and
                  various settings.
                </li>
                <li>
                  <strong className="text-black">Security Cookies:</strong> We
                  use Security Cookies for security purposes.
                </li>
                <li>
                  <strong className="text-black">Advertising Cookies:</strong>{" "}
                  Advertising Cookies are used to serve you with advertisements
                  that may be relevant to you and your interests.
                </li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-medium mb-4 tracking-tight">
                Use of Data
              </h2>
              <p className="text-black/70 font-geist leading-relaxed mb-4">
                Hanif Studio uses the collected data for various purposes:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-black/70 font-geist">
                <li>To provide and maintain our Service</li>
                <li>To notify you about changes to our Service</li>
                <li>
                  To allow you to participate in interactive features of our
                  Service when you choose to do so
                </li>
                <li>To provide customer support</li>
                <li>
                  To gather analysis or valuable information so that we can
                  improve our Service
                </li>
                <li>To monitor the usage of our Service</li>
                <li>To detect, prevent and address technical issues</li>
                <li>
                  To provide you with news, special offers and general
                  information about other goods, services and events which we
                  offer
                </li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-medium mb-4 tracking-tight">
                Retention of Data
              </h2>
              <p className="text-black/70 font-geist leading-relaxed mb-4">
                We will retain your Personal Data only for as long as is
                necessary for the purposes set out in this Privacy Policy. We
                will retain and use your Personal Data to the extent necessary
                to comply with our legal obligations, resolve disputes, and
                enforce our legal agreements and policies.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-medium mb-4 tracking-tight">
                Transfer of Data
              </h2>
              <p className="text-black/70 font-geist leading-relaxed mb-4">
                Your information, including Personal Data, may be transferred to
                — and maintained on — computers located outside of your state,
                province, country or other governmental jurisdiction where the
                data protection laws may differ from those of your jurisdiction.
              </p>
              <p className="text-black/70 font-geist leading-relaxed">
                Hanif Studio will take all the steps reasonably necessary to
                ensure that your data is treated securely and in accordance with
                this Privacy Policy and no transfer of your Personal Data will
                take place to an organisation or a country unless there are
                adequate controls in place including the security of your data
                and other personal information.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-medium mb-4 tracking-tight">
                Disclosure of Data
              </h2>
              <p className="text-black/70 font-geist leading-relaxed mb-4">
                We may disclose personal information that we collect, or you
                provide:
              </p>
              <h3 className="text-xl font-medium mb-3 tracking-tight mt-6">
                Disclosure for Law Enforcement
              </h3>
              <p className="text-black/70 font-geist leading-relaxed mb-4">
                Under certain circumstances, we may be required to disclose your
                Personal Data if required to do so by law or in response to
                valid requests by public authorities.
              </p>
              <h3 className="text-xl font-medium mb-3 tracking-tight mt-6">
                Business Transaction
              </h3>
              <p className="text-black/70 font-geist leading-relaxed">
                If we or our subsidiaries are involved in a merger, acquisition
                or asset sale, your Personal Data may be transferred.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-medium mb-4 tracking-tight">
                Security of Data
              </h2>
              <p className="text-black/70 font-geist leading-relaxed">
                The security of your data is important to us but remember that
                no method of transmission over the Internet or method of
                electronic storage is 100% secure. While we strive to use
                commercially acceptable means to protect your Personal Data, we
                cannot guarantee its absolute security.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-medium mb-4 tracking-tight">
                Your Data Protection Rights Under GDPR
              </h2>
              <p className="text-black/70 font-geist leading-relaxed mb-4">
                If you are a resident of the European Union (EU) and European
                Economic Area (EEA), you have certain data protection rights,
                covered by GDPR.
              </p>
              <p className="text-black/70 font-geist leading-relaxed mb-4">
                We aim to take reasonable steps to allow you to correct, amend,
                delete, or limit the use of your Personal Data. If you wish to
                be informed what Personal Data we hold about you and if you want
                it to be removed from our systems, please email us at
                hanifyaskur@gmail.com.
              </p>
              <p className="text-black/70 font-geist leading-relaxed mb-4">
                In certain circumstances, you have the following data protection
                rights:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-black/70 font-geist">
                <li>
                  The right to access, update or to delete the information we
                  have on you
                </li>
                <li>
                  The right of rectification. You have the right to have your
                  information rectified if that information is inaccurate or
                  incomplete
                </li>
                <li>
                  The right to object. You have the right to object to our
                  processing of your Personal Data
                </li>
                <li>
                  The right of restriction. You have the right to request that
                  we restrict the processing of your personal information
                </li>
                <li>
                  The right to data portability. You have the right to be
                  provided with a copy of your Personal Data in a structured,
                  machine-readable and commonly used format
                </li>
                <li>
                  The right to withdraw consent. You also have the right to
                  withdraw your consent at any time where we rely on your
                  consent to process your personal information
                </li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-medium mb-4 tracking-tight">
                Your Data Protection Rights under CalOPPA
              </h2>
              <p className="text-black/70 font-geist leading-relaxed mb-4">
                CalOPPA is the first state law in the nation to require
                commercial websites and online services to post a privacy
                policy.
              </p>
              <p className="text-black/70 font-geist leading-relaxed mb-4">
                According to CalOPPA we agree to the following:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-black/70 font-geist mb-4">
                <li>Users can visit our site anonymously</li>
                <li>
                  Our Privacy Policy link includes the word "Privacy", and can
                  easily be found on our website
                </li>
                <li>
                  Users will be notified of any privacy policy changes on our
                  Privacy Policy Page
                </li>
                <li>
                  Users are able to change their personal information by
                  emailing us at hanifyaskur@gmail.com
                </li>
              </ul>
              <h3 className="text-xl font-medium mb-3 tracking-tight mt-6">
                Our Policy on "Do Not Track" Signals
              </h3>
              <p className="text-black/70 font-geist leading-relaxed">
                We honor Do Not Track signals and do not track, plant cookies,
                or use advertising when a Do Not Track browser mechanism is in
                place.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-medium mb-4 tracking-tight">
                Your Data Protection Rights under CCPA
              </h2>
              <p className="text-black/70 font-geist leading-relaxed mb-4">
                If you are a California resident, you are entitled to learn what
                data we collect about you, ask to delete your data and not to
                sell (share) it. To exercise your data protection rights, you
                can make certain requests and ask us:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-black/70 font-geist mb-4">
                <li>
                  What personal information we have about you. If you make this
                  request, we will return to you the categories and specific
                  pieces of personal information we have collected about you.
                </li>
                <li>
                  To delete your personal information. If you make this request,
                  we will delete the personal information we hold about you as
                  of the date of your request from our records.
                </li>
                <li>
                  To stop selling your personal information. We don't sell or
                  rent your personal information to any third parties for any
                  purpose.
                </li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-medium mb-4 tracking-tight">
                Service Providers
              </h2>
              <p className="text-black/70 font-geist leading-relaxed mb-4">
                We may employ third party companies and individuals to
                facilitate our Service ("Service Providers"), provide Service on
                our behalf, perform Service-related services or assist us in
                analysing how our Service is used.
              </p>

              <h3 className="text-xl font-medium mb-3 tracking-tight mt-6">
                Analytics
              </h3>
              <p className="text-black/70 font-geist leading-relaxed mb-4">
                We may use third-party Service Providers to monitor and analyze
                the use of our Service.
              </p>
              <p className="text-black/70 font-geist leading-relaxed mb-4">
                <strong className="text-black">Google Analytics:</strong> Google
                Analytics is a web analytics service offered by Google that
                tracks and reports website traffic. Google uses the data
                collected to track and monitor the use of our Service. This data
                is shared with other Google services.
              </p>
              <p className="text-black/70 font-geist leading-relaxed">
                For more information on the privacy practices of Google, please
                visit:{" "}
                <a
                  href="https://policies.google.com/privacy"
                  className="text-blue-600 hover:underline"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  https://policies.google.com/privacy
                </a>
              </p>

              <h3 className="text-xl font-medium mb-3 tracking-tight mt-6">
                Payments
              </h3>
              <p className="text-black/70 font-geist leading-relaxed mb-4">
                We may provide paid products and/or services within Service. In
                that case, we use third-party services for payment processing
                (e.g. payment processors).
              </p>
              <p className="text-black/70 font-geist leading-relaxed mb-4">
                We will not store or collect your payment card details. That
                information is provided directly to our third-party payment
                processors whose use of your personal information is governed by
                their Privacy Policy.
              </p>
              <p className="text-black/70 font-geist leading-relaxed mb-4">
                The payment processor we work with is:
              </p>
              <p className="text-black/70 font-geist leading-relaxed">
                <strong className="text-black">Stripe:</strong> Their Privacy
                Policy can be viewed at:{" "}
                <a
                  href="https://stripe.com/privacy"
                  className="text-blue-600 hover:underline"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  https://stripe.com/privacy
                </a>
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-medium mb-4 tracking-tight">
                Links to Other Sites
              </h2>
              <p className="text-black/70 font-geist leading-relaxed mb-4">
                Our Service may contain links to other sites that are not
                operated by us. If you click a third party link, you will be
                directed to that third party's site. We strongly advise you to
                review the Privacy Policy of every site you visit.
              </p>
              <p className="text-black/70 font-geist leading-relaxed">
                We have no control over and assume no responsibility for the
                content, privacy policies or practices of any third party sites
                or services.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-medium mb-4 tracking-tight">
                Children's Privacy
              </h2>
              <p className="text-black/70 font-geist leading-relaxed mb-4">
                Our Services are not intended for use by children under the age
                of 13 ("Children").
              </p>
              <p className="text-black/70 font-geist leading-relaxed">
                We do not knowingly collect personally identifiable information
                from Children under 13. If you become aware that a Child has
                provided us with Personal Data, please contact us. If we become
                aware that we have collected Personal Data from Children without
                verification of parental consent, we take steps to remove that
                information from our servers.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-medium mb-4 tracking-tight">
                Changes to This Privacy Policy
              </h2>
              <p className="text-black/70 font-geist leading-relaxed mb-4">
                We may update our Privacy Policy from time to time. We will
                notify you of any changes by posting the new Privacy Policy on
                this page.
              </p>
              <p className="text-black/70 font-geist leading-relaxed mb-4">
                We will let you know via email and/or a prominent notice on our
                Service, prior to the change becoming effective and update
                "effective date" at the top of this Privacy Policy.
              </p>
              <p className="text-black/70 font-geist leading-relaxed">
                You are advised to review this Privacy Policy periodically for
                any changes. Changes to this Privacy Policy are effective when
                they are posted on this page.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-medium mb-4 tracking-tight">
                Contact Us
              </h2>
              <p className="text-black/70 font-geist leading-relaxed">
                If you have any questions about this Privacy Policy, please
                contact us by email:{" "}
                <a
                  href="mailto:hanifyaskur@gmail.com"
                  className="text-blue-600 hover:underline"
                >
                  hanifyaskur@gmail.com
                </a>
              </p>
            </section>
          </div>
        </main>

        <Footer />
      </div>
    </div>
  );
}
